<?php

namespace Xif6\NewsrssBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FluxHttpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxHttpRepository extends EntityRepository
{
}
