acme_store_homepage:
    pattern:  /store/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_store_product_create:
    pattern: /product/create
    defaults: { _controller: AcmeStoreBundle:Default:create }

acme_store_product_show:
    pattern: /product/show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }
