<?php

namespace AppBundle\Repository;

/**
 * FluxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxRepository extends \Doctrine\ORM\EntityRepository
{
}
