imports:
    - { resource: parameters.yml }
    - { resource: parameters_db.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: assetic.yml }
    - { resource: fos_elastica.yml }
    - { resource: knp_paginator.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Mopa bootstrap Configuration
mopa_bootstrap:
    form: ~  # Adds twig form theme  support
    menu: ~  # enables twig helpers for menu

# Braincrafted bootstrap Configuration
#braincrafted_bootstrap:
#    assets_dir: %kernel.root_dir%/../vendor/twitter/bootstrap
#    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-*.min.js
#    less_filter: lessphp

# FOSUser Configuration
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Xif6\NewsrssBundle\Entity\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
