app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '@AppBundle/Controller/Api/DefaultController.php'
    type: rest
    prefix: api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"