acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

acme_task_annotaion:
    resource: "@AcmeTaskBundle/Controller"
    prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

acme_blog_annotation:
    resource: "@AcmeBlogBundle/Controller"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_store_annotation:
    resource: "@AcmeStoreBundle/Controller"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

