routing_locale:
    resource: "routing_locale.yml"
    prefix:   /{_locale}
    defaults:
        _locale: %locale%
    requirements:
        _locale: en|fr

routing_locale_old:
    pattern:  /actualite-{id}-{slug}.{_format}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: xif6_newsrss_flux
        permanent: true
    requirements:
        id: \d+
        slug: ".+"
        _format: html|json
