acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

acme_task_annotaion:
    resource: "@AcmeTaskBundle/Controller"
    prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

acme_blog_annotation:
    resource: "@AcmeBlogBundle/Controller"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_store_annotation:
    resource: "@AcmeStoreBundle/Controller"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

admin_annotation:
    resource: "@AcmeSecurityBundle/Controller"
    prefix:   /

admin:
    pattern:    /admin
    defaults:   { _controller: AcmeSecurityBundle:Security:admin }

#authentification
#login:
#    pattern:    /login
#    defaults:   { _controller: AcmeSecurityBundle:Security:login }

#login_check:
#    pattern:    /login_check

#logout:
#    pattern:    /logout


#   FOS
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


