parameters:
    newsrss.parser.french_date_time.class: NewsrssBundle\Parser\LocaleDateTime
    newsrss.parser.locale_date_time.french:
        timezone: 'Europe/Paris'
        regex:
            - { pattern: '/(.{5,10})jan(v?)(\.?)(ier)?\b/iu', replacement: '\1Jan'}
            - { pattern: '/(.{5,10})f[e|é]v(r?)(\.?)(ier)?\b/iu', replacement: '\1Feb'}
            - { pattern: '/(.{5,10})mar(s?)(\.?)\b/iu', replacement: '\1Mar'}
            - { pattern: '/(.{5,10})avr(\.?)(il)?\b/iu', replacement: '\1Apr'}
            - { pattern: '/(.{5,10})mai\b/iu', replacement: '\1May'}
            - { pattern: '/(.{5,10})jui(\.?)(n?)\b/iu', replacement: '\1Jun'}
            - { pattern: '/(.{5,10})juil(\.?)(let)?\b/iu', replacement: '\1Jul'}
            - { pattern: '/(.{5,10})ao[u|ù](\.?)(t?)\b/iu', replacement: '\1Aug'}
            - { pattern: '/(.{5,10})sep(\.?)(t?)(\.?)(embre)?\b/iu', replacement: '\1Sep'}
            - { pattern: '/(.{5,10})oct(\.?)(obre)?\b/iu', replacement: '\1Oct'}
            - { pattern: '/(.{5,10})nov(\.?)(embre)?\b/iu', replacement: '\1Nov'}
            - { pattern: '/(.{5,10})d[e|é]c(\.?)(embre)?\b/iu', replacement: '\1Dec'}
            - { pattern: '/^lun(\.?)(di)?/iu', replacement: 'Mon'}
            - { pattern: '/^mar(\.?)(di)?/iu', replacement: 'Tue'}
            - { pattern: '/^mer(\.?)(credi)?/iu', replacement: 'Wed'}
            - { pattern: '/^jeu(\.?)(di)?/iu', replacement: 'Thu'}
            - { pattern: '/^ven(\.?)(dredi)?/iu', replacement: 'Fri'}
            - { pattern: '/^sam(\.?)(edi)?/iu', replacement: 'Sat'}
            - { pattern: '/^dim(\.?)(anche)?/iu', replacement: 'Sun'}
            - { pattern: '/\bof\b/iu', replacement: ''}
            - { pattern: '/([0-3]?[0-9])\/([01]?[0-9])\/([0-9]{2,4})/iu', replacement: '\3/\2/\1'}

services:
    newsrss.parser.french_date_time:
        class: %newsrss.parser.french_date_time.class%
        arguments: [%newsrss.parser.locale_date_time.french%]
