acme_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeBlogBundle:Default:index }

#acme_blog_valid:
#    pattern:  /blog/valid/{name}
#    defaults: { _controller: AcmeBlogBundle:Default:valid }
