<?php

namespace Xif6\NewsrssBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Xif6\NewsrssBundle\Document\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends DocumentRepository
{
    public function checkUnique(Item $item)
    {
        $qb = $this->createQueryBuilder();

        $result = $qb->find()
            ->addAnd(
                $qb->expr()->field('flux_id')->equals($item->getFluxId())
                    ->addOr($qb->expr()->field('title')->equals($item->getTitle()))
                    ->addOr($qb->expr()->field('url')->equals($item->getUrl()))
            )
            ->getQuery()
            ->getSingleResult();

        if ($result) {
            $item->setId($result->getId());
        }
    }
}