parameters:
    xif6_newsrss.encoding.class: Xif6\NewsrssBundle\Service\Encoding
    xif6_newsrss.encoding.detect_order:
        - ASCII
        - UTF-8
        - ISO-8859-15
        - UTF-16BE
        - UTF-16LE
        - UTF-16
        - UTF-32BE
        - UTF-32LE
        - UTF-32
        - JIS
        - EUC-JP
        - EUC-KR
        - EUC-CN
        - EUC-TW
        - SJIS
        - Windows-1251
        - Windows-1252
        - KOI8-R

    xif6_newsrss.encoding.html_entity_maps:
        128: 8364
        129: 160
        130: 8218
        131: 402
        132: 8222
        133: 8230
        134: 8224
        135: 8225
        136: 710
        137: 8240
        138: 352
        139: 8249
        140: 338
        141: 160
        142: 381
        143: 160
        144: 160
        145: 8216
        146: 8217
        147: 8220
        148: 8221
        149: 8226
        150: 8211
        151: 8212
        152: 732
        153: 8482
        154: 353
        155: 8250
        156: 339
        157: 160
        158: 382
        159: 376


services:
    xif6_newsrss.encoding:
        class: %xif6_newsrss.encoding.class%
        calls:
            - [ setDetectOrder, [ %xif6_newsrss.encoding.detect_order% ] ]
            - [ setHtmlEntityMaps, [ %xif6_newsrss.encoding.html_entity_maps% ] ]