xif6_newsrss_annotation:
    resource: "@Xif6NewsrssBundle/Controller"

xif6_newsrss_homepage:
    pattern: /
    defaults:
        _controller: Xif6NewsrssBundle:Default:index

xif6_newsrss_category:
    resource: "@Xif6NewsrssBundle/Resources/config/routing/category.yml"
    prefix: /category

xif6_newsrss_flux:
    resource: "@Xif6NewsrssBundle/Resources/config/routing/flux.yml"
    prefix: /flux

xif6_newsrss_item:
    resource: "@Xif6NewsrssBundle/Resources/config/routing/item.yml"
    prefix: /item

xif6_newsrss_user:
    resource: "@Xif6NewsrssBundle/Resources/config/routing/user.yml"
    prefix: /user

xif6_newsrss_search:
    resource: "@Xif6NewsrssBundle/Resources/config/routing/search.yml"
    prefix: /search



xif6_newsrss_hello:
    pattern:  /hello/{name}
    defaults: { _controller: Xif6NewsrssBundle:Default:hello }
