imports:
    - { resource: parser/rss.yml }
    - { resource: parser/locale_date_time.yml }
#    - { resource: @Xif6NewsrssBundle/Resources/config/crawler.xml }
    - { resource: crawler.xml }

parameters:
    xif6_newsrss.listener.document.class: Xif6\NewsrssBundle\EventListener\DocumentListener
#    xif6_newsrss.example.class: Xif6\NewsrssBundle\Example

services:
#    xif6_newsrss.listener:
#        class: %xif6_newsrss.listener.document.class%
#        tags:
#            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
#    xif6_newsrss.example:
#        class: %xif6_newsrss.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]




