parameters:
#    xif6_newsrss.example.class: Xif6\NewsrssBundle\Example

services:
#    xif6_newsrss.example:
#        class: %xif6_newsrss.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
