newsrss_category_index:
    path: /{path}-{id}.{_format}
    defaults:
        _controller: NewsrssBundle:Category:index
        _format: html
    requirements:
        id: \d+
        path: ".+"
        _format: html|json

newsrss_category_arbo:
    path: /arbo.{_format}
    defaults:
        _controller: NewsrssBundle:Category:arbo
        _format: html
    requirements:
        _format: html|json

