newsrss_item_index:
    path: /{id}-{type}.{_format}
    defaults:
        _controller: NewsrssBundle:Item:index
        _format: html
    requirements:
        id: \d+
        type: default|user
        _format: html|json

newsrss_item_most_users:
    path: /most-users.{_format}
    defaults:
        _controller: NewsrssBundle:Item:mostUsers
        _format: html
    requirements:
        _format: html|json
