newsrss_user_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        _format: html
        template: 'NewsrssBundle:User:index.html.twig'
    requirements:
        _format: html

newsrss_user_fluxes:
    path: /fluxes.{_format}
    defaults:
        _controller: NewsrssBundle:User:fluxes
        _format: json
    requirements:
        _format: json

newsrss_user_items:
    path: /items.{_format}
    defaults:
        _controller: NewsrssBundle:User:items
        _format: json
    requirements:
        _format: json

newsrss_user_item:
    path: /item/{fluxId}.{_format}
    defaults:
        _controller: NewsrssBundle:User:item
        _format: json
    requirements:
        _format: json
